### ISSUE TITLE
Value matrix initialization

### ISSUE THREAD

**Issue by Jibril-Frej** [persai-lab/EDM2021-DMKT#1]
Is there a reason why the value matrix is initialized randomly at each forward pass in [dmkt.py](https://github.com/persai-lab/EDM2021-DMKT/blob/0ab1cbfb219d107526a21f62e7d1e2e256130f6f/deepkt/graphs/models/dmkt.py#L78)? 
Should not the initial value of the value matrix  be part of the model parameter ?
Isn't there a risk of having inconsistent results during the test phase ?
Did I miss something ?

```
self.value_matrix = torch.Tensor(self.num_concepts, self.value_dim).to(self.device)
nn.init.normal_(self.value_matrix, mean=0., std=self.init_std)
self.value_matrix = self.value_matrix.clone().repeat(batch_size, 1, 1)
```

Thank you

**Comment by Chunpai** [comment]
Hi @Jibril-Frej, 

Great question. The value matrix is not part of the model parameter since it needs to be updated over time. Instead, we need to learn the "add" and "erase" layers to update the value matrix.  The main reason of random initialization is the batch prediction, which means the long learning trajectories are truncated or cropped into fixed size ( and short sequences are padded) for both training and testing. The random initialization could generalize well. Hope this helps. Let me know if you have other questions. 

Thanks, 
Chunpai

**Comment by Jibril-Frej** [comment]
Hi @Chunpai ,

Thanks for your answer. 

I agree that the value matrix $M^v_t$ needs to be updated over time and therefore is not part of the model’s parameters but the initial value $M^v_0$ should be part of the model’s parameters as stated in the section 2.3.4 of the [DKVMN](https://arxiv.org/pdf/1611.08108.pdf) paper. If we have a random initialization of $M^v_0$ at each forward pass, the model will make different predictions for the same learning trajectories.

However, in practice, when we tested both approaches on our own dataset, (random $M^v_0$ at each forward pass and $M^v_0$ as part of the learned parameters), we did not observe a significant difference in student performance prediction.

Do you know of other work that used or studied this approach?

Many thanks,
Jibril

**Comment by Chunpai** [comment]
@Jibril-Frej I think DKVMN also uses the random initialization in their code. I don’t think we could learn the initial value matrix and update layers together, which may lead to the identification problem. That means if initial values changes, the update layers could be changed to have same performance. For testing, you could set a same random seed for both training and testing. Hope this helps.
